server:
  port: 8080
spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://zipkin:9411/}
  mvc:
    view:
      suffix: .html
      prefix: /
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: ${productms.datasource.url}
    username: ${productms.datasource.username}
    password: ${productms.datasource.password}
    driver-class-name: ${productms.datasource.driver}
  jpa:
    show-sql: true
  cloud:
    bus:
      destination: configXchange
  rabbitmq:
   host: ${rabbitmq.host:localhost}
   port: ${rabbitmq.port:5672}
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"

#feign:
#  hystrix:
#   enabled: true
